# Generated by Django 3.2.5 on 2021-07-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
