# Generated by Django 3.2.5 on 2021-07-14 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление воспитательной работы',
                'verbose_name_plural': 'Направления воспитательных работ',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Формат мероприятия',
                'verbose_name_plural': 'Форматы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень мероприятия',
                'verbose_name_plural': 'Уровни мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль СибГУ',
                'verbose_name_plural': 'Роли СибГУ',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название мероприятия')),
                ('free_plan', models.BooleanField(default=False, verbose_name='Включить в сводный план')),
                ('educational_work_in_opop', models.BooleanField(default=False, verbose_name='Воспитательная работа в рамках ОПОП')),
                ('hours_count', models.PositiveSmallIntegerField(verbose_name='Количество часов')),
                ('educational_work_outside_opop', models.BooleanField(default=True, verbose_name='Воспитательная работа за пределами ОПОП')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('stop_date', models.DateField(verbose_name='Дата окончания')),
                ('place', models.CharField(max_length=256, verbose_name='Место проведения')),
                ('coverage_participants_plan', models.PositiveSmallIntegerField(verbose_name='Охват участников (план)')),
                ('number_organizers', models.PositiveSmallIntegerField(blank=True, verbose_name='Из них организаторов')),
                ('coverage_participants_fact', models.PositiveSmallIntegerField(verbose_name='Охват участников (факт)')),
                ('links', models.TextField(verbose_name='Ссылки на материалы в интернете о мероприятии (факт)')),
                ('verified_date', models.DateField(verbose_name='Дата верификации')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.direction', verbose_name='Направление воспитательной работы')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.format', verbose_name='Формат мероприятия')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.level', verbose_name='Уровень мероприятия')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organization', verbose_name='Ответственное подразделение')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_events', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.role', verbose_name='Роль СибГУ')),
                ('verified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто верифицировал')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event', verbose_name='Пост')),
            ],
        ),
    ]
