# Generated by Django 3.2.5 on 2021-07-14 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='coverage_participants_fact',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Охват участников (факт)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hours_count',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='event',
            name='links',
            field=models.TextField(blank=True, verbose_name='Ссылки на материалы в интернете о мероприятии (факт)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stop_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='verified',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто верифицировал'),
        ),
        migrations.AlterField(
            model_name='event',
            name='verified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата верификации'),
        ),
    ]
