# Generated by Django 3.2.5 on 2021-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_comment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hours_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество часов'),
        ),
    ]
