# Generated by Django 3.2.5 on 2021-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_number_organizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coverage_participants_fact',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Охват участников (факт)'),
        ),
    ]
