# Generated by Django 3.2.5 on 2021-08-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210831_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.CharField(blank=True, max_length=512, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.direction', verbose_name='Направление воспитательной работы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organization', verbose_name='Ответственное подразделение'),
        ),
    ]
