# Generated by Django 3.2.7 on 2022-04-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_importantdate_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
