# Generated by Django 3.2.7 on 2022-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('rejected ', 'Отклоненно'), ('in_process', 'В обработке'), ('wait_for_report', 'В ожидании отчета'), ('verified', 'Верефицированно')], default='in_process', max_length=15, verbose_name='Статус Мероприятия'),
        ),
    ]
