# Generated by Django 3.2.7 on 2022-08-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_description'),
        ('events', '0021_alter_event_status'),
    ]

    operations = [
    ]
