# Generated by Django 3.2.7 on 2022-08-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_merge_0019_event_description_0021_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='educational_work_outside_opop',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible',
        ),
    ]
