# Generated by Django 3.2.7 on 2022-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20220825_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiztor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='position',
        ),
        migrations.AddField(
            model_name='event',
            name='organizators',
            field=models.ManyToManyField(blank=True, null=True, to='events.Organiztor'),
        ),
    ]
