# Generated by Django 3.2.7 on 2022-08-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20220829_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantDate',
        ),
    ]
