# Generated by Django 3.2.7 on 2022-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_eventgroup_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
