# Generated by Django 3.2.7 on 2022-12-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='stop_date',
        ),
    ]
