# Generated by Django 3.2.7 on 2022-12-21 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0031_eventgroup_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='description',
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
