# Generated by Django 3.2.7 on 2022-12-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20221222_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='test', max_length=512, verbose_name='Название мероприятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organization', verbose_name='Ответственное подразделение'),
        ),
    ]
