# Generated by Django 3.2.7 on 2022-12-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20221222_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='coverage_participants_fact',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Охват участников (факт.)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='links',
            field=models.TextField(blank=True, verbose_name='Ссылки на материалы в интернете о мероприятии (факт.)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='organizators',
            field=models.ManyToManyField(blank=True, null=True, to='events.Organiztor', verbose_name='Организаторы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='place_fact',
            field=models.CharField(max_length=512, verbose_name='Место проведения факт.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date_fact',
            field=models.DateField(verbose_name='Дата начала Факт.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='stop_date_fact',
            field=models.DateField(verbose_name='Дата конца Факт.'),
        ),
    ]
