# Generated by Django 3.2.7 on 2022-12-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20221223_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('0', 'Отклоненно'), ('1', 'В обработке'), ('2', 'В ожидании отчета'), ('3', 'Верефицированно'), ('4', 'Отчет отклонен'), ('5', 'В ожидании верефикации отчета')], default='1', max_length=1, verbose_name='Статус Мероприятия'),
        ),
    ]
