# Generated by Django 3.2.7 on 2023-01-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_event_is_transferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Роль организатора')),
            ],
            options={
                'verbose_name': 'Роль организатора',
                'verbose_name_plural': 'Роли организатора',
            },
        ),
        migrations.AlterField(
            model_name='organiztor',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organizatorrole'),
        ),
    ]
