# Generated by Django 3.2.7 on 2023-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20230130_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizatorrole',
            options={'verbose_name': 'Роль организатора', 'verbose_name_plural': 'Роли организаторов'},
        ),
        migrations.AddField(
            model_name='event',
            name='count_index',
            field=models.TextField(default='', verbose_name='Колличественный показатель'),
        ),
        migrations.AlterField(
            model_name='event',
            name='direction',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Направление воспитательных работ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Уровень мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответственное подразделение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='role',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Роль СибГУ'),
        ),
    ]
