# Generated by Django 3.2.7 on 2024-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_report_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_inside',
            field=models.BooleanField(default=False, verbose_name='Внутреннее?'),
        ),
    ]
