# Generated by Django 3.2.7 on 2024-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_level_is_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивировать мероприятие'),
        ),
    ]
