# Generated by Django 3.2.5 on 2021-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_hours_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_organizers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Из них организаторов'),
        ),
    ]
