# Generated by Django 3.2.5 on 2021-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_coverage_participants_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='verified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата верификации'),
        ),
    ]
