# Generated by Django 3.2.6 on 2021-08-31 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210831_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.format', verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.level', verbose_name='Уровень мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.role', verbose_name='Роль СибГУ'),
        ),
    ]
