# Generated by Django 3.2.7 on 2022-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('default', 'Обычный пользователь'), ('author', 'Автор'), ('moder', 'Модератор'), ('admin', 'Администратор')], default='default', max_length=8, verbose_name='Роль'),
        ),
    ]
