# Generated by Django 3.2.7 on 2022-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Автор'), ('moder', 'Модератор'), ('admin', 'Администратор')], default='author', max_length=6, verbose_name='Роль'),
        ),
    ]
