# Generated by Django 3.2.7 on 2022-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.IntegerField(choices=[(0, 'Автор'), (1, 'Модератор'), (2, 'Администратор'), (3, 'Супер администратор')], verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Автор'), (1, 'Модератор'), (2, 'Администратор'), (3, 'Супер администратор')], default=0, verbose_name='Роль'),
        ),
    ]
