# Generated by Django 3.2.7 on 2022-08-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
    ]
