# Generated by Django 3.2.7 on 2022-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='position',
            field=models.TextField(blank=True, default='', help_text='Должность или группа', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.IntegerField(choices=[(0, 'Студент'), (1, 'Сотрудник')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_info',
            field=models.TextField(blank=True, default='', help_text='Контактная информация', verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.TextField(blank=True, default='', help_text='Должность или группа', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Студент'), (1, 'Сотрудник')], default=0, verbose_name='Статус'),
        ),
    ]
