# Generated by Django 3.2.7 on 2022-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220826_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_messenger',
            field=models.TextField(blank=True, default='', verbose_name='Мессенджер для связи'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default='', max_length=13, verbose_name='Контактный телефон'),
        ),
    ]
