# Generated by Django 3.2.7 on 2023-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='contact_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
